// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utlecbgtbcylcuznnznm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0bGVjYmd0YmN5bGN1em5uem5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzQ2NzgsImV4cCI6MjA2NTgxMDY3OH0.5VLTIGT8grFCok_AAabVTZHGstU0yMwyXNVq2bftp7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);